# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: velocities.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='velocities.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x10velocities.proto\"5\n\nVelocities\x12\x12\n\nlinear_vel\x18\x01 \x01(\x02\x12\x13\n\x0b\x61ngular_vel\x18\x02 \x01(\x02\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_VELOCITIES = _descriptor.Descriptor(
  name='Velocities',
  full_name='Velocities',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='linear_vel', full_name='Velocities.linear_vel', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='angular_vel', full_name='Velocities.angular_vel', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=73,
)

DESCRIPTOR.message_types_by_name['Velocities'] = _VELOCITIES

Velocities = _reflection.GeneratedProtocolMessageType('Velocities', (_message.Message,), dict(
  DESCRIPTOR = _VELOCITIES,
  __module__ = 'velocities_pb2'
  # @@protoc_insertion_point(class_scope:Velocities)
  ))
_sym_db.RegisterMessage(Velocities)


# @@protoc_insertion_point(module_scope)
