/* Automatically generated nanopb header */
/* Generated by 0.4.1-dev */

#ifndef PB_STATUS_MESSAGE_PB_H_INCLUDED
#define PB_STATUS_MESSAGE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _VelocityCommand_Status {
    VelocityCommand_Status_UNKNOWN = 0,
    VelocityCommand_Status_WAITING_CONFIG = 1,
    VelocityCommand_Status_READY = 2,
    VelocityCommand_Status_RUNNING = 3,
    VelocityCommand_Status_H_BRIDGE_FAULT_1 = 4,
    VelocityCommand_Status_H_BRIDGE_FAULT_2 = 5,
    VelocityCommand_Status_UNKNOWN_ERROR = 6
} VelocityCommand_Status;

/* Struct definitions */
typedef struct _VelocityCommand {
    float linear_velocity;
    float angular_velocity;
    uint64_t delta_millis;
    VelocityCommand_Status status;
} VelocityCommand;


/* Helper constants for enums */
#define _VelocityCommand_Status_MIN VelocityCommand_Status_UNKNOWN
#define _VelocityCommand_Status_MAX VelocityCommand_Status_UNKNOWN_ERROR
#define _VelocityCommand_Status_ARRAYSIZE ((VelocityCommand_Status)(VelocityCommand_Status_UNKNOWN_ERROR+1))


/* Initializer values for message structs */
#define VelocityCommand_init_default             {0, 0, 0, _VelocityCommand_Status_MIN}
#define VelocityCommand_init_zero                {0, 0, 0, _VelocityCommand_Status_MIN}

/* Field tags (for use in manual encoding/decoding) */
#define VelocityCommand_linear_velocity_tag      1
#define VelocityCommand_angular_velocity_tag     2
#define VelocityCommand_delta_millis_tag         3
#define VelocityCommand_status_tag               4

/* Struct field encoding specification for nanopb */
#define VelocityCommand_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    linear_velocity,   1) \
X(a, STATIC,   SINGULAR, FLOAT,    angular_velocity,   2) \
X(a, STATIC,   SINGULAR, FIXED64,  delta_millis,      3) \
X(a, STATIC,   SINGULAR, UENUM,    status,            4)
#define VelocityCommand_CALLBACK NULL
#define VelocityCommand_DEFAULT NULL

extern const pb_msgdesc_t VelocityCommand_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define VelocityCommand_fields &VelocityCommand_msg

/* Maximum encoded size of messages (where known) */
#define VelocityCommand_size                     21

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
