/* Automatically generated nanopb constant definitions */
/* Generated by 0.4.1-dev */

#include "velocity_command.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(VelocityCommand, VelocityCommand, AUTO)



