/* Automatically generated nanopb constant definitions */
/* Generated by 0.4.1-dev */

#include "otto_communication.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(StatusMessage, StatusMessage, AUTO)


PB_BIND(ConfigCommand, ConfigCommand, AUTO)


PB_BIND(VelocityCommand, VelocityCommand, AUTO)




